#!/bin/bash

# Args
URL=""
COOKIE=""
OUTPUT=""

# Configs
EXT="png"

# Globals
FRAME_URL=""
CONTENT_ID=""
CONTENT_BASE_URL=""

function parse_args() {
	# GNU getopt
	OPTIONS=$(getopt -o c:o: -l cookie:,output: -- "$@")

	eval set -- $OPTIONS
	while true; do
		case "$1" in
			-c | --cookie ) shift; COOKIE="$1" ;;
			-o | --output ) shift; OUTPUT="$1" ;;
			-- ) shift; URL="$1"; break ;;
			* ) break ;;
		esac
		shift
	done
}

function read_args_if_not_given() {
	OK=true
	
	if [ "$URL" = "" ]; then
		echo -n "Lecture URL: "
		read URL
	fi

	if [ "$COOKIE" = "" ]; then
		echo -n "Cookie(MoodleSession): "
		read COOKIE
	fi

	if [ "$OUTPUT" = "" ]; then
		echo -n "Output directory: "
		read OUTPUT
	fi
}

function assert_args() {
	OK=true
	
	if [ "$URL" = "" ]; then
		echo "No url specified."
		OK=false
	fi

	if [ "$COOKIE" = "" ]; then
		echo "No cookie specified."
		OK=false
	fi

	if [ "$OUTPUT" = "" ]; then
		echo "No output directory specified."
		OK=false
	fi

	if [ "$OK" = false ]; then
		usage
	fi
}

function usage() {
	echo "Usage: ./lms-get <url> --cookie <sessionid> --output <dirname>"
	exit 1
}

function parse_frame_url() {
	FRAME_URL=$(curl -b "MoodleSession=$COOKIE" $URL | grep "iframe_document" | grep -oEi "http://[\.a-zA-Z0-9\/\?=-_&]+")
}

function parse_content_id() {
	CONTENT_ID=$(echo $FRAME_URL | grep -oEi "fn=[a-z0-9]+" | awk -F '=' '{print $2}')
	echo $CONTENT_ID
}

function generate_content_base_url() {
	CONTENT_BASE_URL="http://cyber.inu.ac.kr/ubion_document/$CONTENT_ID/$CONTENT_ID.files"
}

function download_contents() {
	mkdir -p $OUTPUT

	file_number=1
	url="$CONTENT_BASE_URL/$file_number.$EXT"
	status_code=$(curl -o /dev/null -w "%{http_code}" $url)

	while [ $status_code -eq 200 ]; do
		curl -o $OUTPUT/$file_number.$EXT $url
		
		file_number=$((file_number + 1))
		url="$CONTENT_BASE_URL/$file_number.$EXT"
		status_code=$(curl -o /dev/null -w "%{http_code}" $url)
	done
}

parse_args $@
read_args_if_not_given
assert_args

parse_frame_url
parse_content_id

generate_content_base_url
download_contents
