#!/bin/bash

# Args
URL=""
TOKEN=""
OUTPUT=""

# Globals
FRAME_URL=""
ORIGIN_EXT=""
CONTENT_ID=""
CONTENT_BASE_URL=""

function parse_args() {
	# GNU getopt
	OPTIONS=$(getopt -o t:o: -l token:,output: -- "$@")

	eval set -- $OPTIONS
	while true; do
		case "$1" in
			-t | --token ) shift; TOKEN="$1" ;;
			-o | --output ) shift; OUTPUT="$1" ;;
			-- ) shift; URL="$1"; break ;;
			* ) break ;;
		esac
		shift
	done
}

function read_args_if_not_given() {
	OK=true
	
	if [ "$URL" = "" ]; then
		echo -n "Lecture URL: "
		read URL
	fi

	if [ "$TOKEN" = "" ]; then
		echo -n "TOKEN: "
		read COOKIE
	fi

	if [ "$OUTPUT" = "" ]; then
		echo -n "Output directory: "
		read OUTPUT
	fi
}

function assert_args() {
	OK=true
	
	if [ "$URL" = "" ]; then
		echo "No url specified."
		OK=false
	fi

	if [ "$TOKEN" = "" ]; then
		echo "No token specified."
		OK=false
	fi

	if [ "$OUTPUT" = "" ]; then
		echo "No output directory specified."
		OK=false
	fi

	if [ "$OK" = false ]; then
		usage
	fi
}

function usage() {
	echo "Usage: ./lms-get <url> --token <token> --output <dirname>"
	exit 1
}

function parse_origin_ext() {
	ORIGIN_EXT=$(curl -sS -b "MoodleSession=$COOKIE" $URL | grep "keywords" | grep -oEi "\.[a-zA-Z]+" | awk -F '.' '{print $2}')
	echo "Origin ext: $ORIGIN_EXT"
}

function parse_frame_url() {
	FRAME_URL=$(curl -sS -b "MoodleSession=$COOKIE" $URL | grep "iframe_document" | grep -oEi "http://[\.a-zA-Z0-9\/\?=-_&]+")
}

function parse_content_id() {
	CONTENT_ID=$(echo $FRAME_URL | grep -oEi "fn=[a-z0-9]+" | awk -F '=' '{print $2}')
	echo "Content ID: $CONTENT_ID"
}

function generate_content_base_url() {
	CONTENT_BASE_URL="http://cyber.inu.ac.kr/ubion_document/$CONTENT_ID/$CONTENT_ID.files"
}

function download_contents() {
	mkdir -p $OUTPUT

	file_number=1
	url=$(get_url $file_number)
	echo "Getting $url"
	status_code=$(curl -sS -o /dev/null -w "%{http_code}" $url)
	
	while [ $status_code -eq 200 ]; do
		curl -sS -o $OUTPUT/$file_number.$(get_ext) $url
		
		file_number=$((file_number + 1))
		url=$(get_url $file_number)
		echo "Getting $url"
		status_code=$(curl -sS -o /dev/null -w "%{http_code}" $url)
	done
}

function get_url() {
	file_number="$1"

	if [ "$ORIGIN_EXT" = "pptx" ] || [ "$ORIGIN_EXT" = "ppt" ]; then
		echo "$CONTENT_BASE_URL/$(echo $CONTENT_ID)_$(printf '%05d' $((file_number - 1))).$(get_ext)"

	elif [ "$ORIGIN_EXT" = "pdf" ]; then
		echo "$CONTENT_BASE_URL/$file_number.$(get_ext)"
	fi
}

function get_ext() {
	if [ "$ORIGIN_EXT" = "pptx" ] || [ "$ORIGIN_EXT" = "ppt" ]; then
		echo "xhtml"

	elif [ "$ORIGIN_EXT" = "pdf" ]; then
		echo "png"
	fi
}

parse_args $@
read_args_if_not_given
assert_args

parse_origin_ext
parse_frame_url
parse_content_id

generate_content_base_url
download_contents
